var qAndA = {
  questions: [
    'question1',
    'question2',
    'question3',
    'question4',
    'question5',
    'question6',
    'question7',
    'question8',
    'question9',
  ],
  answer1: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer2: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer3: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer4: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer5: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer6: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer7: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer8: ['answer1', 'answer2', 'answer3', 'answer4'],
  answer9: ['answer1', 'answer2', 'answer3', 'answer4'],
};
